Repository openHPI/codeocean, pull requests merged in 2025-07, with the labels that each got.

#2999 Migrate mailers to use parametrized attributes
  app/controllers/comments_controller.rb
  app/controllers/request_for_comments_controller.rb
  app/jobs/detect_exercise_anomalies_job.rb
  app/mailers/user_mailer.rb
  spec/mailers/previews/user_mailer_preview.rb
  spec/mailers/user_mailer_spec.rb
  spec/system/authentication_system_spec.rb
Labels: enhancement, ruby

#2997 Migrate .js.erb files to .js
  app/assets/javascripts/editor/editor.js
  app/assets/javascripts/editor/participantsupport.js
  app/helpers/exercise_helper.rb
  app/views/exercises/_editor.html.slim
  config/initializers/assets.rb
Labels: enhancement, javascript

#3010 chore: Remove unused jRuby environment
  spec/factories/execution_environment.rb
Labels: ruby

#3017 test: Add tests for comment policy
  app/policies/comment_policy.rb
  spec/policies/comment_policy_spec.rb
Labels: ruby

#3045 chore: Enable Rubocop for migrations
  .rubocop.yml
  .rubocop_todo.yml
Labels: enhancement

#3040 fix: Theme selection event listeners
  lib/assets/javascripts/color_mode_picker.js
Labels: bug
